'use client';
import { useEffect, useState } from 'react';
import { SeoEditor, adminInput, adminButton } from '../components/SeoEditor';
import { GoogleReport, type AnalyticsReport } from '../components/GoogleReport';
import type { SeoValues } from '@/app/lib/seo-shared';
type Report = {settings: SeoValues; ai: {enabled: boolean; hasKey: boolean; hasGoogle: boolean; model: string}; products: {id: string; name: string}[]; content: {id: string; titleEn: string}[]; records: {entityType: string; entityId: string; values: SeoValues; audit: {score: number; issues: string[]}}[]; keywords: {id: string; term: string; locale: string; clicks: number | null; impressions: number | null; position: number | null; source: string}[]};
export default function SeoAdmin() {
  const [report, setReport] = useState<Report | null>(null), [values, setValues] = useState<SeoValues>({});
  const [target, setTarget] = useState('settings'), [key, setKey] = useState(''), [enabled, setEnabled] = useState(false), [model, setModel] = useState('gpt-4o-mini');
  const [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [term, setTerm] = useState(''), [locale, setLocale] = useState('ar');
  const [metrics, setMetrics] = useState({clicks: '', impressions: '', position: ''});
  const [analyticsJson, setAnalyticsJson] = useState(''), [analyticsResult, setAnalyticsResult] = useState('');
  const [analyticsReport, setAnalyticsReport] = useState<AnalyticsReport | null>(null);
  async function load() {const res = await fetch('/api/admin/seo'); const data = await res.json(); if (!res.ok) throw new Error(data.error); setReport(data); setEnabled(data.ai.enabled); setModel(data.ai.model); return data as Report;}
  useEffect(() => {load().then(data => setValues(data.settings)).catch(e => setNotice(e.message));}, []);
  async function act(body: Record<string, unknown>) {
    setBusy(true); setNotice('');
    try {const res = await fetch('/api/admin/seo', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body)}); const data = await res.json(); if (!res.ok) throw new Error(data.error); await load(); setNotice('Saved / تم الحفظ'); return true;} catch(e) {setNotice(e instanceof Error ? e.message : 'Failed'); return false;} finally {setBusy(false);}
  }
  function select(value: string) {setTarget(value); if (value === 'settings') setValues(report?.settings || {}); else {const [type, id] = value.split(':'); setValues(report?.records.find(r => r.entityType === type && r.entityId === id)?.values || {});}}
  const [entityType, entityId] = target.split(':');
  return <div className="max-w-5xl mx-auto space-y-7 text-chocolate-50">
    <header><h1 className="text-3xl font-semibold">SEO & visibility / الظهور والبحث</h1><p className="text-chocolate-300 mt-2">Manage search information, sharing, generation and target keywords.</p></header>
    {notice && <p role="status" className="rounded-lg border border-chocolate-700 p-3 text-gold-300">{notice}</p>}
    {!report ? <p>Loading settings…</p> : <>
      <label className="block"><span className="block mb-2">Edit SEO for</span><select className={adminInput} value={target} onChange={e => select(e.target.value)}><option value="settings">Site defaults / إعدادات عامة</option>{['home', 'menu', 'about', 'contact', 'journal', 'collections', 'occasions', 'campaigns', 'categories', 'pages'].map(id => <option value={`page:${id}`} key={id}>{id}</option>)}{report.products.map(p => <option key={p.id} value={`product:${p.id}`}>{p.name}</option>)}{report.content.map(p => <option key={p.id} value={`content:${p.id}`}>{p.titleEn}</option>)}</select></label>
      <SeoEditor key={target} value={values} onChange={setValues} entity={target === 'settings' ? undefined : {type: entityType, id: entityId}} />
      {target === 'settings' && <div className="grid gap-4 md:grid-cols-2">{(['googleVerification', 'bingVerification', 'gaPropertyId', 'gaMeasurementId', 'searchConsoleSite'] as const).map(field => <label key={field}>{field}<input className={adminInput} value={values[field] || ''} onChange={e => setValues({...values, [field]: e.target.value})}/></label>)}</div>}
      <button disabled={busy} className={adminButton} onClick={() => act(target === 'settings' ? {action: 'settings', values} : {action: 'record', entityType, entityId, values})}>Save SEO / حفظ</button>
      <section className="space-y-4 border-t border-chocolate-800 pt-6"><h2 className="text-xl font-semibold">AI generation / توليد اختياري</h2><p className="text-sm text-chocolate-300">{report.ai.hasKey ? 'A key is saved securely. Leave this field empty to keep it.' : 'No API key saved. Local generation works without a key.'}</p><label className="block">OpenAI API key<input className={adminInput} type="password" autoComplete="new-password" value={key} onChange={e => setKey(e.target.value)} /></label><label className="block">Model<input className={adminInput} value={model} onChange={e => setModel(e.target.value)}/></label><label className="block"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)}/> Enable AI suggestions</label><div className="flex flex-wrap gap-3"><button disabled={busy} className={adminButton} onClick={async () => {if(await act({action: 'ai', apiKey: key || undefined, enabled, model})) setKey('');}}>Save AI settings</button><button disabled={busy} className="text-sm underline" onClick={async () => {if(await act({action: 'ai', clearKey: true, enabled: false, model})) setKey('');}}>Remove saved key</button></div><p className="text-xs text-chocolate-300">AI sends only the content you generate from to OpenAI. Requests may incur provider charges.</p></section>
      <section className="space-y-3 border-t border-chocolate-800 pt-6"><h2 className="text-xl font-semibold">Content checks</h2><button className={adminButton} disabled={busy} onClick={() => act({action: 'fillMissing'})}>Generate missing product SEO locally</button><p className="text-sm text-chocolate-300">Checks measure field completeness, not Google rankings.</p><div className="overflow-x-auto"><table className="w-full text-sm text-start"><thead><tr><th className="p-2 text-start">Page</th><th className="p-2 text-start">Checks</th><th className="p-2 text-start">Suggestions</th></tr></thead><tbody>{report.records.map(r => <tr key={`${r.entityType}:${r.entityId}`} className="border-t border-chocolate-800"><td className="p-2"><button className="underline text-gold-300" onClick={() => select(`${r.entityType}:${r.entityId}`)}>{r.values.titleEn || r.entityId}</button></td><td className="p-2">{r.audit.score}/100</td><td className="p-2">{r.audit.issues.join(', ') || 'Complete'}</td></tr>)}</tbody></table></div></section>
      <section className="space-y-3 border-t border-chocolate-800 pt-6"><h2 className="text-xl font-semibold">Target keywords</h2><p className="text-sm text-chocolate-300">Select a page above, then add its target phrase. Metrics entered here are marked manual.</p><div className="grid gap-3 md:grid-cols-2"><label>Phrase<input className={adminInput} value={term} onChange={e => setTerm(e.target.value)}/></label><label>Language<select className={adminInput} value={locale} onChange={e => setLocale(e.target.value)}><option value="ar">العربية</option><option value="en">English</option></select></label>{(['clicks', 'impressions', 'position'] as const).map(field => <label key={field}>{field}<input type="number" min="0" step={field === 'position' ? '0.1' : '1'} className={adminInput} value={metrics[field]} onChange={e => setMetrics({...metrics, [field]: e.target.value})}/></label>)}</div><button disabled={busy || target === 'settings' || !term} className={adminButton} onClick={() => act({action: 'keyword', term, locale, entityType, entityId, ...metrics})}>Save keyword</button>{report.keywords.map(k => <div key={k.id} className="flex flex-wrap justify-between gap-2 border-t border-chocolate-800 py-2 text-sm"><span>{k.term} · {k.locale} · {k.clicks ?? '—'} clicks · {k.impressions ?? '—'} impressions · position {k.position ?? '—'} · {k.source}</span><button className="underline" disabled={busy} onClick={() => act({action: 'deleteKeyword', id: k.id})}>Delete</button></div>)}</section>
      <section className="space-y-3 border-t border-chocolate-800 pt-6"><h2 className="text-xl font-semibold">Analytics & Search Console</h2><p className="text-sm text-chocolate-300">{report.ai.hasGoogle ? 'A Google connection is saved securely. ' : 'No Google connection saved. '}Connect your Google service account to read real GA4 and search performance. Grant it access to the relevant property first.</p><label className="block">Service account credentials (JSON)<textarea className={adminInput} rows={3} value={analyticsJson} onChange={e => setAnalyticsJson(e.target.value)} placeholder="Paste here to save securely; stored credentials are never displayed." /></label><div className="flex gap-3 flex-wrap"><button className={adminButton} disabled={busy || !analyticsJson} onClick={async () => {setBusy(true); try {const res = await fetch('/api/admin/seo/analytics', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({credentials: analyticsJson})}); if (!res.ok) throw new Error(); setAnalyticsJson(''); await load(); setNotice('Google credentials saved');} catch {setNotice('Could not save Google credentials');} finally {setBusy(false);}}}>Save Google connection</button><button className="text-sm underline" disabled={busy || !report.ai.hasGoogle} onClick={async () => {const res = await fetch('/api/admin/seo/analytics', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({remove:true})}); if(res.ok) {await load(); setNotice('Google connection removed');}}}>Remove Google connection</button><button className={adminButton} disabled={busy || !report.ai.hasGoogle} onClick={async () => {setBusy(true); try {const res = await fetch('/api/admin/seo/analytics', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'syncKeywords'})}); const data = await res.json(); if(!res.ok) throw new Error(data.error); await load(); setNotice(`Synced ${data.synced} search queries`);} catch(e) {setNotice(e instanceof Error ? e.message : 'Sync failed');} finally {setBusy(false);}}}>Sync search keywords</button><button className={adminButton} onClick={async () => {setBusy(true); try {const res = await fetch('/api/admin/seo/analytics'); const data = await res.json(); if(!res.ok) throw new Error(data.error); setAnalyticsReport(data); setAnalyticsResult('');} catch(e) {setAnalyticsResult(e instanceof Error ? e.message : 'Unavailable');} finally {setBusy(false);}}} disabled={busy}>Read last 28 days</button></div>{analyticsResult && <p role="status" className="text-amber-300 text-sm">{analyticsResult}</p>}{analyticsReport && <GoogleReport report={analyticsReport}/>}</section>
    </>}
  </div>;
}
