'use client';
import { useEffect, useState } from 'react';
import { SeoEditor, adminInput, adminButton } from '../components/SeoEditor';
import { contentPath, type SeoValues } from '@/app/lib/seo-shared';
type Page = {id?: string; kind: string; slug: string; titleAr: string; titleEn: string; summaryAr: string; summaryEn: string; bodyAr: string; bodyEn: string; image: string; imageAltAr: string; imageAltEn: string; status: string; publishAt: string; productIds: string[]; categoryId: string; attributeKeys: string[]; history?: {at: string}[]};
const empty: Page = {kind: 'ARTICLE', slug: '', titleAr: '', titleEn: '', summaryAr: '', summaryEn: '', bodyAr: '', bodyEn: '', image: '', imageAltAr: '', imageAltEn: '', status: 'DRAFT', publishAt: '', productIds: [], categoryId: '', attributeKeys: []};
export default function ContentAdmin() {
  const [pages, setPages] = useState<Page[]>([]), [products, setProducts] = useState<{id: string; name: string}[]>([]), [categories, setCategories] = useState<{id: string; name: string}[]>([]);
  const [form, setForm] = useState<Page | null>(null), [seo, setSeo] = useState<SeoValues>({}), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  async function load() {const res = await fetch('/api/admin/content'); const data = await res.json(); if (!res.ok) throw new Error(data.error); setPages(data.pages); setProducts(data.products); setCategories(data.categories);}
  useEffect(() => {load().catch(e => setNotice(e.message));}, []);
  async function edit(p: Page) {setForm({...p, categoryId: p.categoryId || '', publishAt: p.publishAt ? new Date(new Date(p.publishAt).getTime() - new Date(p.publishAt).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''}); setSeo({}); const res = await fetch(`/api/admin/seo?entityType=content&entityId=${p.id}`); if (res.ok) setSeo((await res.json()).values);}
  async function save(extra: Record<string, unknown> = {}) {
    if (!form) return;
    setBusy(true); setNotice('');
    try {const res = await fetch('/api/admin/content', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({...form, publishAt: form.publishAt ? new Date(form.publishAt).toISOString() : null, seo, ...extra})}); const data = await res.json(); if (!res.ok) throw new Error(data.error); await load(); if (extra.action !== 'delete') await edit(data); else setForm(null); setNotice('Saved / تم الحفظ');} catch(e) {setNotice(e instanceof Error ? e.message : 'Failed');} finally {setBusy(false);}
  }
  return <div className="max-w-5xl mx-auto text-chocolate-50 space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-semibold">Content & collections / المحتوى والمجموعات</h1><p className="text-chocolate-300 mt-2">Publish bilingual guides, collections, occasions and campaign pages.</p></div><button className={adminButton} onClick={() => {setForm({...empty}); setSeo({});}}>New page / صفحة جديدة</button></header>{notice && <p role="status" className="text-gold-300">{notice}</p>}
    {form && <form onSubmit={e => {e.preventDefault(); save();}} className="space-y-5 border border-chocolate-800 rounded-xl p-5">
      <div className="grid gap-4 md:grid-cols-2"><label>Page type<select className={adminInput} value={form.kind} onChange={e => setForm({...form, kind: e.target.value})}>{Object.entries({ARTICLE: 'Article / مقال', COLLECTION: 'Collection / مجموعة', OCCASION: 'Occasion / مناسبة', CAMPAIGN: 'Campaign / حملة', CATEGORY: 'Category / تصنيف', PAGE: 'Page / صفحة'}).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>URL name / اسم الرابط<input required className={adminInput} value={form.slug} onChange={e => setForm({...form, slug: e.target.value})} placeholder="chocolate-gift-boxes"/></label>
        {(['titleAr', 'titleEn', 'summaryAr', 'summaryEn', 'bodyAr', 'bodyEn', 'image', 'imageAltAr', 'imageAltEn'] as const).map(field => <label key={field} className={field.startsWith('body') ? 'md:col-span-2' : ''}><span className="block mb-1">{{titleAr: 'عنوان عربي', titleEn: 'English title', summaryAr: 'ملخص عربي', summaryEn: 'English summary', bodyAr: 'المحتوى العربي', bodyEn: 'English content', image: 'Cover image URL', imageAltAr: 'وصف الصورة بالعربي', imageAltEn: 'Image description (English)'}[field]}</span><textarea required={field.startsWith('title')} className={adminInput} dir={field.endsWith('Ar') ? 'rtl' : 'ltr'} rows={field.startsWith('body') ? 8 : field.startsWith('summary') ? 3 : 1} value={form[field]} onChange={e => setForm({...form, [field]: e.target.value})}/></label>)}
        <label>Status<select className={adminInput} value={form.status} onChange={e => setForm({...form, status: e.target.value})}><option value="DRAFT">Draft / مسودة</option><option value="PUBLISHED">Published / منشور</option></select></label><label>Publish from / تاريخ النشر<input className={adminInput} type="datetime-local" value={form.publishAt} onChange={e => setForm({...form, publishAt: e.target.value})}/></label>
        <label>Link category<select className={adminInput} value={form.categoryId} onChange={e => setForm({...form, categoryId: e.target.value})}><option value="">No category</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Attribute keys / مفاتيح الخصائص<input className={adminInput} value={form.attributeKeys.join(', ')} onChange={e => setForm({...form, attributeKeys: e.target.value.split(',').map(s => s.trim()).filter(Boolean)})}/></label>
      </div>
      <fieldset className="space-y-2"><legend className="mb-2">Linked products / المنتجات المرتبطة</legend><div className="grid gap-2 max-h-60 overflow-auto md:grid-cols-2">{products.map(p => <label key={p.id} className="text-sm"><input type="checkbox" checked={form.productIds.includes(p.id)} onChange={e => setForm({...form, productIds: e.target.checked ? [...form.productIds, p.id] : form.productIds.filter(id => id !== p.id)})}/> {p.name}</label>)}</div></fieldset>
      <p className="text-xs text-chocolate-300">Content is plain text. Separate paragraphs with a blank line. Draft and scheduled pages are visible only to administrators in preview.</p>
      <SeoEditor value={seo} onChange={setSeo} entity={form.id ? {type: 'content', id: form.id} : undefined} source={{titleAr: form.titleAr, titleEn: form.titleEn, bodyAr: form.summaryAr || form.bodyAr, bodyEn: form.summaryEn || form.bodyEn, image: form.image}}/>
      <div className="flex gap-3 flex-wrap"><button className={adminButton} disabled={busy} type="submit">Save page</button><button type="button" onClick={() => setForm(null)}>Close editor</button>{form.id && <><a className="underline text-gold-300" target="_blank" rel="noreferrer" href={`/ar${contentPath(form)}?preview=1`}>Preview Arabic</a><a className="underline text-gold-300" target="_blank" rel="noreferrer" href={`/en${contentPath(form)}?preview=1`}>Preview English</a><button type="button" disabled={busy} className="text-red-300 underline" onClick={() => {if (confirm('Delete this page?')) save({action: 'delete'});}}>Delete page</button></>}</div>
      {!!form.history?.length && <details><summary className="cursor-pointer text-sm">Previous content versions</summary>{form.history.map((h, i) => <button key={i} disabled={busy} type="button" className="block underline py-2 text-sm" onClick={() => save({restore: i, seo: undefined})}>Restore {new Date(h.at).toLocaleString()}</button>)}</details>}
    </form>}
    <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Page', 'Type', 'Status', 'Action'].map(t => <th key={t} className="text-start p-3">{t}</th>)}</tr></thead><tbody>{pages.map(p => <tr key={p.id} className="border-t border-chocolate-800"><td className="p-3">{p.titleAr}<br/><span className="text-chocolate-300">{p.titleEn}</span></td><td className="p-3">{p.kind}</td><td className="p-3">{p.status}{p.publishAt && ` · ${new Date(p.publishAt).toLocaleString()}`}</td><td className="p-3"><button className="text-gold-300 underline" onClick={() => edit(p)}>Edit</button></td></tr>)}</tbody></table>{!pages.length && <p className="p-5 text-chocolate-300">Create your first article or collection. Drafts stay private until published.</p>}</div>
  </div>;
}
